import Navbar from '@/components/Navbar/Navbar';
import './globals.css';
import TransitionProvider from '@/components/TransitionPRovider/TransitionProvider';

export const metadata = {
  title: 'Sudhanshu.Dev',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body>
        <TransitionProvider> {children}</TransitionProvider>
      </body>
    </html>
  )
}
